services:
  server:
    container_name: server
    build:
      context: .
    image: mokko-server
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=Volia2003
      - DB_NAME=Mokko
    command: gunicorn -c gunicorn.py Mokko.wsgi 
  
  db:
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: "Mokko"
      MYSQL_ROOT_PASSWORD: "Volia2003"
  
  migrate:
    build:
      context: .
    image: mokko-server
    depends_on:
      - db
    volumes:
      - .:/app
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=Volia2003
      - DB_NAME=Mokko
    command: python manage.py migrate
    restart: on-failure
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15672:15672"
  
  celery:
    depends_on:
      - db
      - rabbitmq
    image: mokko-server
    volumes:
      - .:/app
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=Volia2003
      - DB_NAME=Mokko
    command: celery -A Mokko worker -l info --beat
    restart: on-failure

  

  
  