services:
  web:
    container_name: web
    build:
      context: .
    image: mokko
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DATABASE_NAME = "mokko"
      - DATABASE_PASSWORD = "Volia2003"
      - DATABASE_USER = "root"
      - MYSQL_ROOT_PASSWORD = "Volia2003"
    restart: always
  
  migrate:
    image: mokko
    depends_on:
      - database
    volumes:
      - .:/app
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DATABASE_NAME = "mokko"
      - DATABASE_PASSWORD = "Volia2003"
      - DATABASE_USER = "root"
      - MYSQL_ROOT_PASSWORD = "Volia2003"
    command: python manage.py migrate
  
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "56722:5672"
      - "15672:15672"
  
  celery:
    depends_on:
      - database
      - rabbitmq
    image: mokko
    volumes:
      - .:/app
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DATABASE_NAME = "mokko"
      - DATABASE_PASSWORD = "Volia2003"
      - DATABASE_USER = "root"
      - MYSQL_ROOT_PASSWORD = "Volia2003"
    command: celery -A Mokko worker -l info --beat

  database:
    image: mysql:latest
    ports:
      - "33066:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Volia2003"
      MYSQL_DATABASE: "mokko"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "Volia2003"
  
  