# Generated by Django 4.2 on 2023-04-27 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetable',
            name='coffeeshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tables', to='coffeehouse.coffeeshop'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='coffeehouse.freetable'),
        ),
    ]
